### ISSUE TITLE
Recipe Wrapper

### ISSUE THREAD

**Issue by RagingWarrior2** [Jofairden/Tremor#12]
### tModLoader version

version: `0.10.0.2`

### Tremor version

version: `1.3.2`

### Description

When it goes to add the recipes from the Tremor mod it gives me an error saying: 
"The type initializer for 'Tremor.RecipeData' threw an exception.
    at Tremor.RecipeWrapper.RemoveRecipes()
    at Tremor.Tremor.AddRecipes()
    at Terraria.ModLoader.RecipeHooks.AddRecipes()

### Expected behavior 

It should just load in the recipes and then send me back to the main home screen for Terraria for me to pick my world and character.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Reproduction frequency

How often are you reliably able to reproduce this issue?
Whenever there's a new update for the Tremor mod it does this.

### Mods

List all of the mods you are using when reproducing this issue. 
It's appreciated if you could also test this without mods enabled
Just the Tremor mod but if it works I use the Calamity, Thorium, imksushis death counter, imksushis mod, Fargo's Mutant Mod: Summons and Souls, Dual Wielding, Which Mod Is This From, Boss Checklist, Yet Another Boss Health Bar, and MoreAccesories+.

**Comment by Jofairden** [comment]
Duplicate: see #10
