### ISSUE TITLE
All Vanilla/Modded Ores are "glowing"

### ISSUE THREAD

**Issue by CasperTheGhost** [Jofairden/Tremor#35]
### tModLoader version

version: `0.10.1'

### Tremor version

version: `1.3.2.3`

### Description

What happens?: Well, I downloaded the mod correctly through Mod Browser and I load into my world and I can see all the ores through the ground (cause they are kinda glowing) I've tried making a new world and removing the mod (removing the mod stopped the 'glow') So I don't know if it is conflicting with my other mods?

### Expected behavior 

What should be happening?: Absolutely not!

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Reproduction frequency

How often are you reliably able to reproduce this issue?
Discard this if inapplicable

### Mods
https://www.dropbox.com/sh/4oqcknvlr3azjt8/AADqZZ_rbAtOjm1SjItf0ZKEa?dl=0

### Additional Information

I love Tremor mod, always have! I really dont want this to ruin it for me!

**Comment by Jofairden** [comment]
Can you show a screenshot?

**Comment by CasperTheGhost** [comment]
Sure can its exactly the same as a splunker potion, however Ive never used a splunker potion in this world

https://imgur.com/2RgxSwK

**Comment by CasperTheGhost** [comment]
Ok so it fixed itself, weird didnt even relog or restart smh must've been my client, sorry for wasting your time :/

**Comment by Jofairden** [comment]
Odd, looks like the spelunker effect. It might've been applied through a bug, or perhaps some gear you were wearing.

**Comment by CasperTheGhost** [comment]
Potentially, thanks for the help anyways!
