### ISSUE TITLE
Build causes game to crash

### ISSUE THREAD

**Issue by dchen1903** [Jofairden/Tremor#36]
### tModLoader version

version: 0.10.1

### Tremor version

version: 1.3.2.4

### Description

What happens?
The game crashes when building.  
![tremor mod crash](https://user-images.githubusercontent.com/31247512/30785746-23529bb0-a131-11e7-8460-1305c880a066.PNG)

When you go to build.txt and remove languageVersion = 6, it gives an error:  ; expected at MPlayer.cs at line 9 character 52 
![tremor mod error](https://user-images.githubusercontent.com/31247512/30785853-beb1850c-a132-11e7-9d56-9577d94ba840.PNG)

### Expected behavior 

What should be happening?  It should compile and not crash the game.  
Should run

### Steps to Reproduce

1. put Tremor-master source code folder in Mod Sources folder
2. open Terraria, go to Mod Sources, click Build Tremor-master to compile, the game will crash.  
3. open build.txt in source code, remove  languageVersion = 6,   save file 
4. compile again in Terraria Mod Sources, gives error: 
### Reproduction frequency

How often are you reliably able to reproduce this issue?
Always happens

### Mods

List all of the mods you are using when reproducing this issue. 
It's appreciated if you could also test this without mods enabled
No other mods used

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
Discard this if inapplicable

**Comment by Jofairden** [comment]
You are not supposed to build the mod. Download the .tmod on the releases page

**Comment by dchen1903** [comment]
I am trying to make my own mod that causes new enemies to appear when a modded boss is defeated by using downed boss in modWorld.  How do I do that?

**Comment by Jofairden** [comment]
This isn't the place to ask, please use the forum thread or discord server of tModLoader
