### ISSUE TITLE
Dusking is invisible

### ISSUE THREAD

**Issue by YWZMatt** [Jofairden/Tremor#40]
### tModLoader version

version: 0.10.1.1

### Tremor version

version: 1.3.2.7

### Description

Dusking is invisible

### Expected behavior 

What should be happening?

### Steps to Reproduce

1. Summon dusking at appropriate time of day in hardmode
2. Get killed by invisible boss

### Reproduction frequency

100%

### Mods

Tremor only

### Additional Information

Multiplayer

**Comment by Jofairden** [comment]
So, what is Dusking?

**Comment by Jofairden** [comment]
[Dusking](https://spiritmod.gamepedia.com/Dusking) is a Spirit mod boss, please post in the relevant place.
