### ISSUE TITLE
Summoner minion timer

### ISSUE THREAD

**Issue by monkeybug34** [Jofairden/Tremor#41]
Technically not a bug as far as I am aware.
The 1 minute lifespan of all summoner minions provided by the mod is quite distressing.
It really feels like an unneccessary nerf that makes all the modded summon weapons not worth using.
I would like this to be a request to remove the 1 minute lifespan and let minions stay indefinitely, as is in vanilla terraria.

**Comment by zadum4ivii** [comment]
Afaik even if it shows "1 minute duration" it's still infinity duration.

**Comment by Jofairden** [comment]
Hey, this is just a side effect of how it is implemented in Tremor, but pretty much all minions should last until canceled regardless.
