### ISSUE TITLE
Alchemy Item Bug

### ISSUE THREAD

**Issue by tkapa** [Jofairden/Tremor#52]
### tModLoader version

version: 0.10.1.4

### Tremor version

version: 1.3.5.2

### Description

Throwing Alchemical Weapons with The Nitro / Reinforced Burst equipped: Removes the flask's previous effects,  only deals damage on impact with enemy. Does not produce visual effects. 

### Expected behavior 

What should be happening? With the item equipped, should "burst into a short duration flame instead of their standard burst."

### Steps to Reproduce

1. Equip The Nitro / Reinforced Burst
2. Throw a Basic Flask / Lesser Healing Flask at enemy

### Reproduction frequency

How often are you reliably able to reproduce this issue? Happens whenever I throw a flask while either of these items are equipped.

**Comment by Jofairden** [comment]
Long known.

**Comment by alchemistRD** [comment]
this bug occurs in versions 1.3.2.6 and 1.3.2.7, I am using 1.3.2.4 and this problem does not occur. I could not test version 1.3.2.5
